version: "3"
services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=eventio
      - MYSQL_PASSWORD=eventio_pass
      - MYSQL_DATABASE=eventio
      - MYSQL_ROOT_PASSWORD=myrootpassword
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
